# database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scm
    username: root
    password: Santhu@7022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # OAUTH2 CLIENT CONFIGURATION
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 648921675742-2q841rvev2d1i1112bre4j0ch9rukk56.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          github:
            client-id: Iv23liQCsFOZ7ZJXqV8e
            client-secret: bd54f02b073b4ce803805f865610b6a6cf4817b7
            scope:
              - user:email

  # CLODINARY CONFIGURATION
  # cloudinary:
  #   cloud_name: damiybli8
  #   api_key: 289124989143723
  #   api_secret: VYe1Rg9hZdYX1iMyhCWDTqlAaEg

  # EMAIL CONFIGURATION
  # mail:
  #   host: live.smtp.mailtrap.io
  #   port: 587
  #   username: api
  #   password: 7c89ade9c0ce36397829d9dbe66a0329 #nrgn qehm qngf erur
  #   properties:
  #     mail.smtp.auth: true
  #     mail.smtp.starttls.enable: true
  #     domain_name: demomailtrap.com
